/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// EnvSpecListerExpansion allows custom methods to be added to
// EnvSpecLister.
type EnvSpecListerExpansion interface{}

// EnvSpecNamespaceListerExpansion allows custom methods to be added to
// EnvSpecNamespaceLister.
type EnvSpecNamespaceListerExpansion interface{}

// ScaleInSpecListerExpansion allows custom methods to be added to
// ScaleInSpecLister.
type ScaleInSpecListerExpansion interface{}

// ScaleInSpecNamespaceListerExpansion allows custom methods to be added to
// ScaleInSpecNamespaceLister.
type ScaleInSpecNamespaceListerExpansion interface{}

// TrainingJobListerExpansion allows custom methods to be added to
// TrainingJobLister.
type TrainingJobListerExpansion interface{}

// TrainingJobNamespaceListerExpansion allows custom methods to be added to
// TrainingJobNamespaceLister.
type TrainingJobNamespaceListerExpansion interface{}

// TrainingJobSpecListerExpansion allows custom methods to be added to
// TrainingJobSpecLister.
type TrainingJobSpecListerExpansion interface{}

// TrainingJobSpecNamespaceListerExpansion allows custom methods to be added to
// TrainingJobSpecNamespaceLister.
type TrainingJobSpecNamespaceListerExpansion interface{}
